Naiveretrieval + keyword search = Hybrid search


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

In [ ]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]


In [ ]:
query ="keyword-based search"

In [ ]:
import re
def preprocess_text(text):
    # Remove punctuation and special characters
    text = re.sub(r'[^\w\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    return text

In [ ]:
preprocess_documents = [preprocess_text(doc) for doc in documents]

In [ ]:
preprocess_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [ ]:
preprocessesd_query = preprocess_text(query)

In [ ]:
preprocessesd_query

'keywordbased search'

In [ ]:
vector = TfidfVectorizer()

In [ ]:
vector

TfidfVectorizer()

In [ ]:
X=vector.fit_transform(preprocess_documents)

In [ ]:
X.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [ ]:
X.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [ ]:
query_embedding=vector.transform([preprocessesd_query])

In [ ]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [ ]:
similarities = cosine_similarity(X, query_embedding)

In [ ]:
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [ ]:
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()

In [ ]:
ranked_indices

array([1, 3, 2, 0])

In [ ]:
import numpy as np

similarities = np.array([[0.        ],
                         [0.50551777],
                         [0.        ],
                         [0.48693426]])

# Flatten similarities if it's a 2D column vector
similarities = similarities.flatten()

# Get the ranked indices in descending order
ranked_indices = np.argsort(similarities)[::-1]

# Create an array to hold the ranks
ranks = np.empty_like(ranked_indices)
ranks[ranked_indices] = np.arange(len(similarities))

print("Similarities:", similarities)
print("Ranked Indices:", ranked_indices)
print("Ranks:", ranks)

Similarities: [0.         0.50551777 0.         0.48693426]
Ranked Indices: [1 3 2 0]
Ranks: [3 0 2 1]


In [ ]:
ranked_documents = [documents[i] for i in ranked_indices]

In [ ]:
for i,doc in enumerate(ranked_documents):
    print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: Document analysis involves extracting keywords.
Rank 4: This is a list which containig sample documents.


In [ ]:
query

'keyword-based search'

In [ ]:
document_embeddings = np.array([
    [0.634, 0.234, 0.867, 0.042, 0.249],
    [0.123, 0.456, 0.789, 0.321, 0.654],
    [0.987, 0.654, 0.321, 0.123, 0.456]
])

In [ ]:
query_embedding = np.array([[0.789, 0.321, 0.654, 0.987, 0.123]])

In [ ]:

# Calculate cosine similarity between query and documents
similarities = cosine_similarity(document_embeddings, query_embedding)

In [ ]:

similarities

array([[0.73558979],
       [0.67357898],
       [0.71517305]])

In [ ]:
ranked_indices = np.argsort(similarities,axis=0)[::-1].flatten()

In [ ]:
ranked_indices

array([0, 2, 1])

In [ ]:
for i,idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: {documents[idx]}")

Rank 1: This is a list which containig sample documents.
Rank 2: Document analysis involves extracting keywords.
Rank 3: Keywords are important for keyword-based search.


hybrid/ensemble search = vector_search+keyword_search